version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: DockerMvc/Dockerfile
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=192.168.10.100,1433;Database=lino;User=sa;Password=Mateo.eras@12"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Mateo.eras@12"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
